### ISSUE TITLE
Dense Regression

### ISSUE THREAD

**Issue by karasjoh000** [ralfbiedert/ffsvm-rust#6]
I am using dense regression SVM model and it is giving all the same values every time. Every prediction yields the same values.

**Comment by karasjoh000** [comment]
nevermind, its how I trained the model lol. Let me do some better prerocessing

**Comment by karasjoh000** [comment]
Nope, it looks like it makes the predictions the same no matter the input.

**Comment by ralfbiedert** [comment]
Thanks for the report! Can you post a model / or app that exhibits the problem?

**Comment by karasjoh000** [comment]
I did not scale the data, might that be the issue?

**Comment by karasjoh000** [comment]
I tested with libsvm/svm-predict, it gives the same results. I will try to scale the data and see if that helps

**Comment by ralfbiedert** [comment]
Yes, I realized the FAQ didn't mention that data should be scaled; added a comment.
