### ISSUE TITLE
Suggestions for better results

### ISSUE THREAD

**Issue by karasjoh000** [ralfbiedert/ffsvm-rust#7]
Hi I am training regression svm using this library, and I get horrible results. I verified with libsvm and it provides the same results. What is a good approach to svm regression? 
Here is what I should get: 
[Screen Shot 2019-03-20 at 1.17.59 AM.pdf](https://github.com/ralfbiedert/ffsvm-rust/files/2987090/Screen.Shot.2019-03-20.at.1.17.59.AM.pdf)
Here is the predicted: 
[Screen Shot 2019-03-20 at 1.18.35 AM.pdf](https://github.com/ralfbiedert/ffsvm-rust/files/2987096/Screen.Shot.2019-03-20.at.1.18.35.AM.pdf)
I tried all possible kernels but I cannot get it to work.
[Screen Shot 2019-03-20 at 1.18.56 AM.pdf](https://github.com/ralfbiedert/ffsvm-rust/files/2987097/Screen.Shot.2019-03-20.at.1.18.56.AM.pdf)
[Screen Shot 2019-03-20 at 1.21.41 AM.pdf](https://github.com/ralfbiedert/ffsvm-rust/files/2987106/Screen.Shot.2019-03-20.at.1.21.41.AM.pdf)

I have 219k data points with 100 dimensions.

**Comment by karasjoh000** [comment]
It is weird with the fact that if I remove features, it becomes more accurate. The more features I add, it becomes less accurate. This is not an issue with the library just asking for some advice.

**Comment by ralfbiedert** [comment]
Without know details, here is what I would do, in this specific order:

1. Start with and **focus on the RBF kernel** (usually gives best results at expense of speed)
1. Make sure the **data is normalized** (sounds like you did)
1. To speed up grid search, **sample a small subset of your data** (e.g., on 1% of your data)
1. Perform **a grid search**, see [FAQ](https://github.com/ralfbiedert/ffsvm-rust/blob/master/docs/FAQ.md#how-can-i-train-a-model) (basically, running `libSVM`'s `grid.py` tool).
1. Apply **parameters you found in grid search**  to training

Doing grid search if you haven't done so can MASSIVELY improve your results.
